# Generated by Django 5.2.5 on 2025-08-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lib_e',
            new_name='game',
        ),
    ]
