# Generated by Django 5.2.5 on 2025-08-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0002_rename_lib_e_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='game',
            new_name='enrollmentdetail',
        ),
    ]
