# Generated by Django 5.2.5 on 2025-08-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0003_rename_game_enrollmentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
