# Generated by Django 5.2.5 on 2025-08-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
